#!/usr/bin/env sh

while read file
do
        case "$1" in
          "w") 
              cp "$file" ~/.config/pape.png &&
              xwallpaper --center "$HOME/.config/pape.png" ;;
	        "r")
		          convert -rotate 90 "$file" "$file" ;;
	        "R")
		          convert -rotate -90 "$file" "$file" ;;
	        "f")
		          convert -flop "$file" "$file" ;;
	        
          "y")
		          echo -n "$file" | xclip -selection clipboard ;;
        esac
done
